version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    networks:
      - app

  app:
    build:
      context: .
    environment:
      DJANGO_SETTINGS_MODULE: app.settings
    ports:
      - "8000:8000"
    networks:
      - app
    depends_on:
      - postgres
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  app: