version: "3.7"

services:
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
  
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: pep_api
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass#123
    ports:
      - "5433:5432"
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      DB_NAME: pep_api
      DB_USER: user
      DB_PASSWORD: pass#123
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      - app
      - postgres
    depends_on:
      - postgres
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  app:
  postgres:

volumes:
  postgres-data:
